name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      #- uses: actions/cache@v2
        #with:
          #path: ~/.npm
          #key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          #restore-keys: |
            #${{ runner.os }}-node-
      - name: Install
        run: npm install
      - name: Build
        uses: GabrielBB/xvfb-action@v1.4
        with:
          run: --server-args="-screen 0" grunt --verbose
      - name: Test
        uses: GabrielBB/xvfb-action@v1.4
        with:
          run: --server-args="-screen 0" grunt coverage
